.PHONY: FORCE
all: FORCE
	$(MAKE) -C .. tyzen_qt test_tyzen_qt
clean: FORCE
	$(MAKE) -C .. tyzen_qt_clean test_tyzen_qt_clean
check: FORCE
	$(MAKE) -C .. test_tyzen_qt_check
tyzen-qt tyzen-qt.exe: FORCE
	 $(MAKE) -C .. tyzen_qt
apk: FORCE
	$(MAKE) -C .. tyzen_qt_apk
